/// Asset paths. Illustrations are generated by tool/illustrations/render.py,
/// empty-state ones by tool/illustrations/empty_states.py.
abstract final class AppImages {
  static const String _base = 'assets/images';

  static const String logo = '$_base/logo.png';
  static const String alarmClock = '$_base/alarm_clock.png';
  static const String medTablet = '$_base/med_tablet.png';
  static const String medCapsule = '$_base/med_capsule.png';
  static const String medInjection = '$_base/med_injection.png';
  static const String medDrops = '$_base/med_drops.png';
  static const String medInhaler = '$_base/med_inhaler.png';
  static const String medCream = '$_base/med_cream.png';
  static const String medSyrup = '$_base/med_syrup.png';
  static const String medOther = '$_base/med_other.png';
  static const String emptyBloodPressure = '$_base/empty_blood_pressure.png';
  static const String emptyBloodSugar = '$_base/empty_blood_sugar.png';
  static const String emptyHistory = '$_base/empty_history.png';
  static const String emptyExpenses = '$_base/empty_expenses.png';
  static const String emptyDoctors = '$_base/empty_doctors.png';
  static const String emptyRecords = '$_base/empty_records.png';
  static const String samplePrescription = '$_base/sample_prescription.jpg';
  static const String sampleLabReport = '$_base/sample_lab_report.jpg';
}
